# Generated by Django 4.1.4 on 2022-12-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Titulo')),
                ('description', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('status', models.CharField(choices=[('1', 'Pendiente'), ('2', 'En proceso'), ('3', 'Finalizado')], max_length=1, verbose_name='Estado')),
                ('deadline', models.DateField(verbose_name='Fecha de Cierre')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'ordering': ['id'],
            },
        ),
    ]
