# Generated by Django 4.1.4 on 2022-12-18 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_nota', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('user',)},
        ),
    ]
